import { gql } from 'apollo-angular-boost';
export const coes = gql`{ 
    coes{
      id
      type
  }  
}`;
export const coe = gql`
query($limit: Int, $start : Int,$where:JSON){
    coes(where:$where){
      blogs{
        description
        thumbnail{
          id
          name
          url
          ext
        }
        id
        _id
        name
      }
      projects{
        id
        status
        tags
        name   
        client{
          id
          _id
          name
        }
        members{
          id
          _id
          employeeId{
            id
            name
            email
            picture{
              id
              name
              url
            }
            location{
              id
              location
            }
          }
        }      
      }
      employees(limit:$limit,start:$start,sort:"name"){
        id
        _id
        name
        email
        description
        picture{
          url
          id
        }
        location{
          location
          id
        }    
      }
    }
  }`;